<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dokter</name>
   <tag></tag>
   <elementGuidId>a5a08bf6-d515-4b04-b9e7-91c701450c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.dokter.l1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, 'https://antrian.medique.id/index.php/d_dokter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7adf21ad-5b4f-40bb-b5fa-1729e23c3e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://antrian.medique.id/index.php/d_dokter</value>
      <webElementGuid>03ea942e-7e7f-4828-9020-0a1afe411202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dokter l1</value>
      <webElementGuid>01ab2c3c-0503-450c-8f18-db806e280213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokter</value>
      <webElementGuid>7f80498f-6fe0-4b55-8839-cee7de3065b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sidebar-mini layout-fixed text-sm layout-navbar-fixed sidebar-open&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar elevation-4 sidebar-light-red sidebar-focused&quot;]/div[@class=&quot;sidebar os-host os-theme-light os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-scrollbar-vertical-hidden os-host-transition&quot;]/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/nav[@class=&quot;mt-2&quot;]/ul[@class=&quot;nav nav-pills nav-sidebar flex-column nav-compact nav-child-indent text-sm&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link dokter l1&quot;]</value>
      <webElementGuid>a11fa390-858a-426e-a136-f4f8b317e3cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://antrian.medique.id/index.php/d_dokter')]</value>
      <webElementGuid>7bfebd5c-67e7-4db3-8560-8da788689614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>09967149-9a92-4d29-a356-101d8fecfab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://antrian.medique.id/index.php/d_dokter' and (text() = 'Dokter' or . = 'Dokter')]</value>
      <webElementGuid>72b44cdb-0d95-425e-a643-3ca75eda1358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
